### ISSUE TITLE
Copycat application

### ISSUE THREAD

**Issue by avipars** [jasonycw/MemeCreator#14]
This developer has been copying and profiting from open source applications. As soon as I saw the screenshots, I realized. https://play.google.com/store/apps/details?id=com.ssaurel.memecreator.pro

I'm going to report him to Google play and leave a bad review on the free version.i suggest you do the same.

It's a shame what he has done.

**Comment by avipars** [comment]
Free version: https://play.google.com/store/apps/details?id=com.ssaurel.memecreator

**Comment by jasonycw** [comment]
Thanks for the report. 
But this project is just using simple MIT licence and was not limited for others to modify which he does.

And I am not sure if they need to credit this repository.

**Comment by avipars** [comment]
You are right. I believe this guy checks the licenses before he takes app
code.

**Comment by Poussinou** [comment]
@avipars @jasonycw 
This guy does'nt respect the MIT License since he doesn't provide the MIT license terms and doesn't credit the original author. Read this [page](https://en.wikipedia.org/wiki/MIT_License) for more information :)

Please reopen this issue and report both apps using [this formular](https://support.google.com/legal/contact/lr_dmca?product=googleplay).
